---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "service.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ include "service.name" . }}
  minReplicas: {{.Values.min.pod }}
  maxReplicas: {{.Values.max.pod }}